#!/bin/bash

:>$LOGROTATE_CONFIG
(
  echo "$LOGROTATE_PATHS {" 
  echo $LOGROTATE_OPTIONS | tr ',' '\n' | sed -E 's/(^\s*|\s*$)//g' | sed 's/^/  /g' 
  echo "}"
) >> $LOGROTATE_CONFIG

/usr/sbin/logrotate -f -s $LOGROTATE_STATE $LOGROTATE_CONFIG

